-- Create CV content table
CREATE TABLE IF NOT EXISTS cv_content (
    id SERIAL PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    location VARCHAR(255),
    website VARCHAR(500),
    linkedin VARCHAR(500),
    github VARCHAR(500),
    summary TEXT NOT NULL,
    technical_skills JSON,
    soft_skills JSON,
    experience JSON,
    education JSON,
    projects JSON,
    certifications JSON,
    languages JSON,
    additional_info JSON,
    template VARCHAR(50) DEFAULT 'modern',
    color_scheme VARCHAR(50) DEFAULT 'blue',
    layout VARCHAR(50) DEFAULT 'single',
    show_photo BOOLEAN DEFAULT false,
    photo_url VARCHAR(500),
    is_active BOOLEAN DEFAULT true,
    is_public BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);
